version: "3"
services:
    judge_server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - $PWD:/code
            - $PWD/tests/test_case:/test_case
            - $PWD/log:/log
            - $PWD/judger/run:/judger/run
        environment:
            - BACKEND_URL=http://backend:80/api/judge_server_heartbeat
            - SERVICE_URL=http://judge-server:12358
            - TOKEN=YOUR_TOKEN_HERE
        command: sleep infinity
        ports:
            - 0.0.0.0:12358:8080
